// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/go-resty/resty/v2"
	"github.com/ktr0731/go-mcp"
	"github.com/miyamo2/hotpepper-gourmet-mcp-server/internal/app/usecases"
	"github.com/miyamo2/hotpepper-gourmet-mcp-server/internal/configs/di/provider"
	"github.com/miyamo2/hotpepper-gourmet-mcp-server/internal/interfaces/handler"
	"github.com/miyamo2/hotpepper-gourmet-mcp-server/internal/interfaces/mcpgen"
)

// Injectors from wire.go:

func GetHandler() *mcp.Handler {
	client := resty.New()
	hotpepperClient := provider.NewHOTPEPPERGOURMETClient(client)
	resourceUsecase := usecases.NewResourceUsecase(hotpepperClient)
	resourceHandler := handler.NewResourceHandler(resourceUsecase)
	toolUseCase := usecases.NewToolUseCase(hotpepperClient)
	toolHandler := handler.NewToolHandler(toolUseCase)
	mcpHandler := mcpgen.NewHandler(resourceHandler, toolHandler)
	return mcpHandler
}
